### ISSUE TITLE
Add a more beautiful UI

### ISSUE THREAD

**Issue by srikarg89** [abagali1/click#1]
The css currently looks suspiciously similar to the Othello website. I'm not accusing you of copying anything, but making it a little bit more distinct might be nice.

**Comment by abagali1** [comment]
shut up

**Comment by JayChen35** [comment]
Can't you just download the Beautiful UI package on VSCode?

**Comment by srikarg89** [comment]
Yeah, I think this issue needs to be reopened. Hasn't been solved yet

**Comment by abagali1** [comment]
beauty is in the eye of the beholder. you clearly need better eyes
